In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [36]:
df = pd.read_csv("/content/qoute_dataset.csv") #dataset of quotes

In [37]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [38]:
df.shape

(3038, 2)

In [39]:
quotes = df["quote"]
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

**Data Preprocessing**

(before applying lstm or anything as such , we nede to preprocess our data, and for that we needa use NLP techniques like vectorization , embeddings , tokenization etc)

In [40]:
quotes = quotes.str.lower()

In [41]:
#removing punctuations
import string
translator = str.maketrans('', '', string.punctuation) #for every punctuation replace it with empty space
quotes = quotes.apply(lambda x: x.translate(translator)) # "lambda x" -> every single quote in the dataset gets passed one by one

In [42]:
#tokenization (assign a number to each word)
from tensorflow.keras.preprocessing.text import Tokenizer

In [43]:
#the actual vocab size for our df can get pretty large sometimes(eg : 30lakh), but setting such a large number, we dont have enuf cpu nor gpu power for our model to compute that
vocab_size = 10000 #10k is a safe number which hopefully captures all the important words
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [44]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10] #8978 unique words and the top 10 most occuring words is printed

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [45]:
sequence = tokenizer.texts_to_sequences(quotes)

The quotes and their corresponding sequentially tokenized vectors are displayed

In [46]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [47]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

For our input and output variable, our project is sentence completion, i.e, we are actively predicting the next word

eg: look at the first quote, if we write "the" [713] , it should predict "world" [62]

similarly if we write "the world" [713,62]. output : "as" [29]

In [48]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    X.append(seq[:i]) #input sequence
    y.append(seq[i]) #output sequence

In [49]:
max_len = 50

In [50]:
#padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding = "pre")

In [51]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [52]:
X_padded.shape

(85271, 50)

In [53]:
y = np.array(y)
y.shape

(85271,)

Our models like LSTM or GRU work with probabilities (0 and 1), so we need to one hot encode our output variable (y)
suppose y stores a tokenized word [121]
its one hot encoded to the vocab size, in it the position where the word is stored is encoded to 1 , the rest is 0, basically 9.9k 0's and only a single 1

[121] -> [0,0,0......1,.....0,0,0]

In [54]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SimpleRNN

In [55]:
embedding_units = 50
rnn_units = 128

**Note** : The code application of RNN LSTM and GRU is mostly similar, only the internal working is different

In [56]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_units, input_length=max_len) #this layer creates the embeddings
)

rnn_model.add(
    SimpleRNN(units=rnn_units) #the embeddings come under this simple RNN layer (128 units)
)
rnn_model.add(
    Dense(units=vocab_size, activation="softmax") #output layer
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [66]:
rnn_model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [67]:
rnn_model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 50, 50)         │       500,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 128)            │        22,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10000)          │     1,290,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,812,912 (6.92 MB)

 Trainable params: 1,812,912 (6.92 MB)

 Non-trainable params: 0 (0.00 B)

In [59]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_units, input_length=max_len)
)
lstm_model.add(
    LSTM(units=rnn_units)
)
lstm_model.add(
    Dense(units=vocab_size, activation="softmax")
)

In [70]:
import tensorflow as tf
lstm_model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy", tf.keras.metrics.SparseTopKCategoricalAccuracy(k=5, name='top5')])
lstm_model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [68]:
epochs = 10
batch_size = 128
history_rnn = rnn_model.fit(X_padded, y, epochs=epochs, batch_size=batch_size, validation_split=0.1)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.1974 - loss: 4.4653 - val_accuracy: 0.1059 - val_loss: 6.5476
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.2163 - loss: 4.1898 - val_accuracy: 0.1040 - val_loss: 6.6489
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2412 - loss: 3.9708 - val_accuracy: 0.1037 - val_loss: 6.7636
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2652 - loss: 3.7798 - val_accuracy: 0.1019 - val_loss: 6.8632
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2916 - loss: 3.6139 - val_accuracy: 0.0971 - val_loss: 6.9772
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.3136 - loss: 3.4673 - val_accuracy: 0.0956 - val_loss: 7.0800
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.3342 - loss: 3.3381 - val_accuracy: 0.0944 - val_loss: 7.1660
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.3529 - loss: 3.2215 - val_accuracy: 0.0928 - val_loss: 7.2633
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.3688 - loss: 3.1171 - val_accuracy: 0.0901 - val_loss: 7.3454
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.3852 - loss: 3.0199 - val_accuracy: 0.0930 - val_loss: 7.4294

In [72]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

history_lstm = lstm_model.fit(
    X_padded, y,
    epochs=100,
    batch_size=128,
    validation_split=0.1,

)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.1143 - loss: 5.5149 - top5: 0.2640 - val_accuracy: 0.1035 - val_loss: 6.4820 - val_top5: 0.2397
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.1239 - loss: 5.3515 - top5: 0.2777 - val_accuracy: 0.1086 - val_loss: 6.5173 - val_top5: 0.2438
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.1309 - loss: 5.1981 - top5: 0.2896 - val_accuracy: 0.1080 - val_loss: 6.5589 - val_top5: 0.2489
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1381 - loss: 5.0501 - top5: 0.3028 - val_accuracy: 0.1115 - val_loss: 6.6056 - val_top5: 0.2502
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1457 - loss: 4.9098 - top5: 0.3125 - val_accuracy: 0.1115 - val_loss: 6.6595 - val_top5: 0.2528
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1531 - loss: 4.7762 - top5: 0.3250 - val_accuracy: 0.1121 - val_loss: 6.7263 - val_top5: 0.2528
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.1595 - loss: 4.6487 - top5: 0.3381 - val_accuracy: 0.1136 - val_loss: 6.8068 - val_top5: 0.2536
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.1684 - loss: 4.5234 - top5: 0.3547 - val_accuracy: 0.1103 - val_loss: 6.8673 - val_top5: 0.2515
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.1773 - loss: 4.4054 - top5: 0.3718 - val_accuracy: 0.1126 - val_loss: 6.9326 - val_top5: 0.2542
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1896 - loss: 4.2896 - top5: 0.3913 - val_accuracy: 0.1109 - val_loss: 7.0208 - val_top5: 0.2529
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2034 - loss: 4.1797 - top5: 0.4111 - val_accuracy: 0.1093 - val_loss: 7.0795 - val_top5: 0.2545
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2169 - loss: 4.0745 - top5: 0.4313 - val_accuracy: 0.1113 - val_loss: 7.1680 - val_top5: 0.2518
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2314 - loss: 3.9732 - top5: 0.4473 - val_accuracy: 0.1105 - val_loss: 7.2411 - val_top5: 0.2511
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2462 - loss: 3.8779 - top5: 0.4651 - val_accuracy: 0.1092 - val_loss: 7.3090 - val_top5: 0.2482
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2592 - loss: 3.7879 - top5: 0.4788 - val_accuracy: 0.1076 - val_loss: 7.3922 - val_top5: 0.2499
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2720 - loss: 3.7038 - top5: 0.4925 - val_accuracy: 0.1092 - val_loss: 7.4793 - val_top5: 0.2480
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2836 - loss: 3.6250 - top5: 0.5042 - val_accuracy: 0.1113 - val_loss: 7.5256 - val_top5: 0.2458
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.2942 - loss: 3.5507 - top5: 0.5162 - val_accuracy: 0.1074 - val_loss: 7.6150 - val_top5: 0.2443
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3062 - loss: 3.4803 - top5: 0.5263 - val_accuracy: 0.1071 - val_loss: 7.6770 - val_top5: 0.2443
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3159 - loss: 3.4126 - top5: 0.5388 - val_accuracy: 0.1079 - val_loss: 7.7524 - val_top5: 0.2410
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3256 - loss: 3.3492 - top5: 0.5470 - val_accuracy: 0.1091 - val_loss: 7.8042 - val_top5: 0.2430
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3348 - loss: 3.2876 - top5: 0.5575 - val_accuracy: 0.1034 - val_loss: 7.8817 - val_top5: 0.2375
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3447 - loss: 3.2294 - top5: 0.5666 - val_accuracy: 0.1030 - val_loss: 7.9449 - val_top5: 0.2343
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3542 - loss: 3.1727 - top5: 0.5757 - val_accuracy: 0.1020 - val_loss: 8.0118 - val_top5: 0.2369
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3623 - loss: 3.1188 - top5: 0.5839 - val_accuracy: 0.1021 - val_loss: 8.0742 - val_top5: 0.2330
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3722 - loss: 3.0648 - top5: 0.5925 - val_accuracy: 0.1026 - val_loss: 8.1410 - val_top5: 0.2295
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.3804 - loss: 3.0138 - top5: 0.6008 - val_accuracy: 0.1038 - val_loss: 8.2110 - val_top5: 0.2325
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3877 - loss: 2.9682 - top5: 0.6088 - val_accuracy: 0.1014 - val_loss: 8.2700 - val_top5: 0.2308
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3964 - loss: 2.9166 - top5: 0.6172 - val_accuracy: 0.0981 - val_loss: 8.3245 - val_top5: 0.2289
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4057 - loss: 2.8701 - top5: 0.6249 - val_accuracy: 0.0994 - val_loss: 8.3907 - val_top5: 0.2280
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4111 - loss: 2.8256 - top5: 0.6321 - val_accuracy: 0.0985 - val_loss: 8.4471 - val_top5: 0.2261
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4200 - loss: 2.7815 - top5: 0.6388 - val_accuracy: 0.1006 - val_loss: 8.4990 - val_top5: 0.2254
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4272 - loss: 2.7384 - top5: 0.6455 - val_accuracy: 0.0940 - val_loss: 8.5634 - val_top5: 0.2251
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4338 - loss: 2.6965 - top5: 0.6528 - val_accuracy: 0.0976 - val_loss: 8.6381 - val_top5: 0.2226
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4412 - loss: 2.6565 - top5: 0.6593 - val_accuracy: 0.0971 - val_loss: 8.6850 - val_top5: 0.2246
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4490 - loss: 2.6165 - top5: 0.6657 - val_accuracy: 0.0970 - val_loss: 8.7482 - val_top5: 0.2224
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4558 - loss: 2.5783 - top5: 0.6717 - val_accuracy: 0.0953 - val_loss: 8.8047 - val_top5: 0.2224
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4620 - loss: 2.5409 - top5: 0.6755 - val_accuracy: 0.0953 - val_loss: 8.8559 - val_top5: 0.2219
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4684 - loss: 2.5036 - top5: 0.6841 - val_accuracy: 0.0947 - val_loss: 8.9206 - val_top5: 0.2179
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4753 - loss: 2.4677 - top5: 0.6890 - val_accuracy: 0.0922 - val_loss: 8.9721 - val_top5: 0.2185
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4815 - loss: 2.4328 - top5: 0.6949 - val_accuracy: 0.0929 - val_loss: 9.0258 - val_top5: 0.2181
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4878 - loss: 2.3987 - top5: 0.7006 - val_accuracy: 0.0943 - val_loss: 9.0930 - val_top5: 0.2176
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.4930 - loss: 2.3666 - top5: 0.7055 - val_accuracy: 0.0932 - val_loss: 9.1375 - val_top5: 0.2167
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5004 - loss: 2.3322 - top5: 0.7105 - val_accuracy: 0.0919 - val_loss: 9.2083 - val_top5: 0.2166
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5057 - loss: 2.3012 - top5: 0.7159 - val_accuracy: 0.0944 - val_loss: 9.2433 - val_top5: 0.2151
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5127 - loss: 2.2700 - top5: 0.7198 - val_accuracy: 0.0915 - val_loss: 9.3159 - val_top5: 0.2134
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5171 - loss: 2.2403 - top5: 0.7251 - val_accuracy: 0.0908 - val_loss: 9.3604 - val_top5: 0.2115
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5240 - loss: 2.2095 - top5: 0.7293 - val_accuracy: 0.0904 - val_loss: 9.4156 - val_top5: 0.2106
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5292 - loss: 2.1813 - top5: 0.7347 - val_accuracy: 0.0903 - val_loss: 9.4677 - val_top5: 0.2102
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5343 - loss: 2.1527 - top5: 0.7384 - val_accuracy: 0.0906 - val_loss: 9.5184 - val_top5: 0.2117
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5394 - loss: 2.1253 - top5: 0.7437 - val_accuracy: 0.0899 - val_loss: 9.5735 - val_top5: 0.2077
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5448 - loss: 2.0977 - top5: 0.7467 - val_accuracy: 0.0886 - val_loss: 9.6246 - val_top5: 0.2098
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5504 - loss: 2.0717 - top5: 0.7514 - val_accuracy: 0.0879 - val_loss: 9.6806 - val_top5: 0.2061
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5564 - loss: 2.0440 - top5: 0.7569 - val_accuracy: 0.0877 - val_loss: 9.7441 - val_top5: 0.2030
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5599 - loss: 2.0208 - top5: 0.7601 - val_accuracy: 0.0892 - val_loss: 9.7815 - val_top5: 0.2080
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5650 - loss: 1.9950 - top5: 0.7630 - val_accuracy: 0.0865 - val_loss: 9.8426 - val_top5: 0.2037
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5704 - loss: 1.9705 - top5: 0.7676 - val_accuracy: 0.0903 - val_loss: 9.8954 - val_top5: 0.2046
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.5757 - loss: 1.9464 - top5: 0.7714 - val_accuracy: 0.0898 - val_loss: 9.9491 - val_top5: 0.2059
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5802 - loss: 1.9242 - top5: 0.7742 - val_accuracy: 0.0879 - val_loss: 9.9979 - val_top5: 0.2054
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5837 - loss: 1.9022 - top5: 0.7779 - val_accuracy: 0.0878 - val_loss: 10.0356 - val_top5: 0.2024
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5903 - loss: 1.8771 - top5: 0.7817 - val_accuracy: 0.0871 - val_loss: 10.0981 - val_top5: 0.2029
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5947 - loss: 1.8552 - top5: 0.7851 - val_accuracy: 0.0855 - val_loss: 10.1373 - val_top5: 0.2003
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.5991 - loss: 1.8332 - top5: 0.7882 - val_accuracy: 0.0869 - val_loss: 10.1939 - val_top5: 0.1991
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6025 - loss: 1.8133 - top5: 0.7914 - val_accuracy: 0.0868 - val_loss: 10.2213 - val_top5: 0.1992
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6068 - loss: 1.7929 - top5: 0.7948 - val_accuracy: 0.0857 - val_loss: 10.2846 - val_top5: 0.1950
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6100 - loss: 1.7725 - top5: 0.7971 - val_accuracy: 0.0858 - val_loss: 10.3337 - val_top5: 0.1993
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6140 - loss: 1.7550 - top5: 0.8002 - val_accuracy: 0.0869 - val_loss: 10.3924 - val_top5: 0.1965
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6177 - loss: 1.7338 - top5: 0.8026 - val_accuracy: 0.0864 - val_loss: 10.4181 - val_top5: 0.1985
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6247 - loss: 1.7115 - top5: 0.8062 - val_accuracy: 0.0862 - val_loss: 10.4854 - val_top5: 0.1952
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6270 - loss: 1.6940 - top5: 0.8080 - val_accuracy: 0.0856 - val_loss: 10.5320 - val_top5: 0.1991
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6300 - loss: 1.6776 - top5: 0.8119 - val_accuracy: 0.0860 - val_loss: 10.5691 - val_top5: 0.1955
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6352 - loss: 1.6565 - top5: 0.8147 - val_accuracy: 0.0857 - val_loss: 10.6212 - val_top5: 0.1947
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6386 - loss: 1.6398 - top5: 0.8173 - val_accuracy: 0.0838 - val_loss: 10.6763 - val_top5: 0.1952
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6432 - loss: 1.6231 - top5: 0.8192 - val_accuracy: 0.0830 - val_loss: 10.7142 - val_top5: 0.1932
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6461 - loss: 1.6059 - top5: 0.8216 - val_accuracy: 0.0838 - val_loss: 10.7541 - val_top5: 0.1937
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6496 - loss: 1.5886 - top5: 0.8234 - val_accuracy: 0.0845 - val_loss: 10.8144 - val_top5: 0.1916
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6521 - loss: 1.5740 - top5: 0.8258 - val_accuracy: 0.0849 - val_loss: 10.8608 - val_top5: 0.1942
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6553 - loss: 1.5557 - top5: 0.8287 - val_accuracy: 0.0834 - val_loss: 10.9109 - val_top5: 0.1907
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6598 - loss: 1.5408 - top5: 0.8306 - val_accuracy: 0.0817 - val_loss: 10.9534 - val_top5: 0.1917
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.6633 - loss: 1.5256 - top5: 0.8323 - val_accuracy: 0.0815 - val_loss: 11.0165 - val_top5: 0.1910
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6668 - loss: 1.5085 - top5: 0.8352 - val_accuracy: 0.0835 - val_loss: 11.0574 - val_top5: 0.1922
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6701 - loss: 1.4934 - top5: 0.8385 - val_accuracy: 0.0821 - val_loss: 11.0965 - val_top5: 0.1903
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6729 - loss: 1.4805 - top5: 0.8405 - val_accuracy: 0.0802 - val_loss: 11.1371 - val_top5: 0.1902
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6757 - loss: 1.4653 - top5: 0.8418 - val_accuracy: 0.0823 - val_loss: 11.1804 - val_top5: 0.1900
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6796 - loss: 1.4533 - top5: 0.8432 - val_accuracy: 0.0801 - val_loss: 11.2394 - val_top5: 0.1881
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6818 - loss: 1.4365 - top5: 0.8457 - val_accuracy: 0.0818 - val_loss: 11.2825 - val_top5: 0.1918
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.6864 - loss: 1.4219 - top5: 0.8477 - val_accuracy: 0.0809 - val_loss: 11.3355 - val_top5: 0.1874
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6880 - loss: 1.4092 - top5: 0.8500 - val_accuracy: 0.0814 - val_loss: 11.3473 - val_top5: 0.1873
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6899 - loss: 1.3977 - top5: 0.8507 - val_accuracy: 0.0824 - val_loss: 11.4003 - val_top5: 0.1886
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6930 - loss: 1.3816 - top5: 0.8528 - val_accuracy: 0.0811 - val_loss: 11.4468 - val_top5: 0.1880
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6963 - loss: 1.3696 - top5: 0.8552 - val_accuracy: 0.0787 - val_loss: 11.5069 - val_top5: 0.1864
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.6983 - loss: 1.3576 - top5: 0.8565 - val_accuracy: 0.0803 - val_loss: 11.5395 - val_top5: 0.1884
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7024 - loss: 1.3441 - top5: 0.8582 - val_accuracy: 0.0788 - val_loss: 11.5902 - val_top5: 0.1864
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7038 - loss: 1.3324 - top5: 0.8608 - val_accuracy: 0.0789 - val_loss: 11.6107 - val_top5: 0.1876
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7059 - loss: 1.3226 - top5: 0.8617 - val_accuracy: 0.0775 - val_loss: 11.6696 - val_top5: 0.1853
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7086 - loss: 1.3141 - top5: 0.8632 - val_accuracy: 0.0777 - val_loss: 11.7068 - val_top5: 0.1836
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7121 - loss: 1.2973 - top5: 0.8656 - val_accuracy: 0.0763 - val_loss: 11.7789 - val_top5: 0.1861
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7140 - loss: 1.2860 - top5: 0.8670 - val_accuracy: 0.0780 - val_loss: 11.8229 - val_top5: 0.1867
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.7168 - loss: 1.2747 - top5: 0.8682 - val_accuracy: 0.0802 - val_loss: 11.8341 - val_top5: 0.1843
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7185 - loss: 1.2619 - top5: 0.8695 - val_accuracy: 0.0796 - val_loss: 11.8935 - val_top5: 0.1833

In [73]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [74]:
#word map
index_to_word = {}
for word,index in word_index.items():
  index_to_word[index] = word

In [80]:
def predictor(text,model,tokenizer, max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre') #sequentially tokenize the recieved text and adds padding

  preds = model.predict(seq, verbose=0)
  pred_index = np.argmax(preds)
  pred_word = index_to_word[pred_index]

  return pred_word

In [84]:
testing_text = "what are you "
predicted_word = predictor(testing_text, lstm_model, tokenizer, max_len)
print(predicted_word)

implying

In [85]:
def generate_text(seed_text, n_words, model, tokenizer, max_len):
    for _ in range(n_words):
        next_word = predictor(seed_text, model, tokenizer, max_len)
        if next_word == "":
          break
        seed_text += " " + next_word

    return seed_text

In [87]:
text_to_complete = "a thousand "
print(generate_text(text_to_complete, len(text_to_complete), lstm_model, tokenizer, max_len))

a thousand  times without laughter is a question to the heavens heart it

In [88]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [89]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)